name: Draw Keymap

env:
  FORCE_JAVASCRIPT_ ACTIONS_TO_NODE24: true
on:
  workflow_dispatch:
  push:
    paths:
      - "config/**"
      - .github/workflows/draw.yml
      - keymap_drawer.config.yaml

jobs:
  draw:
    uses: caksoylar/keymap-drawer/.github/workflows/draw-zmk.yml@main
    permissions:
      contents: write
    with:
      commit_message: "update: draw keymaps"
      destination: "commit"
      fail_on_error: ${{ fromJSON(true) }}
